version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./initialize/php/Dockerfile
    image: bk/laravel
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel_app
    volumes:
      - ./:/var/www/laravel_app
      # - ./server_config/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-app-network
    links: 
      - db


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
      - 4433:443

    volumes:
      - ./:/var/www/laravel_app
      - ./server_config/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-app-network
    links:
      - app 



  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./server_config/db/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-app-network

#Docker Networks
networks:
  laravel-app-network:
    driver: bridge
volumes:
#Volumes
  dbdata:
    driver: local